name: Compile Binaries

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  compile:
    name: 'Compile Binaries for x86 64 Unknown Linux GNU'
    runs-on: ubuntu-latest
    env:
      deno-version: v1.x

    steps:
      - name: Setup Repository (${{github.event.repository.name}})
        uses: actions/checkout@v4

      - name: Setup Deno (${{env.deno-version}})
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: ${{env.deno-version}}
      
      - name: Compile Binaries
        run: deno task compile:all
