name: Compile Binaries

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  compile:
    name: 'Compile Binaries'
    runs-on: ubuntu-latest
    env:
      deno-version: v1.x
    strategy:
      matrix:
        include:
          - os: unknown-linux-gnu
            architecture: x86_64

          - os: unknown-linux-gnu
            architecture: aarch64

          - os: apple-darwin
            architecture: x86_64

          - os: apple-darwin
            architecture: aarch64

          - os: pc-windows-msvc
            architecture: x86_64

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4

      - name: 'Setup Deno (${{env.deno-version}})'
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: ${{env.deno-version}}
      
      - name: 'Compiling Binary'
        run: deno task compile:${{matrix.architecture}}-${{matrix.os}}
      
      - name: 'Upload Binary'
        uses: actions/upload-artifact@v4
        with:
          name: 'binaries'
          path: './bin/${{matrix.architecture}}-${{matrix.os}}'
          if-no-files-found: ignore
